### ISSUE TITLE
The database for Asciinema.Repo could not be created

### ISSUE THREAD

**Issue by W1lkins** [asciinema/asciinema-server#303]
Running the `docker-compose` commands on a DigitalOcean droplet, `Ubuntu 16.04` and `Docker version 18.03.0-ce, build 0520e24`:

When I run the command `docker-compose run --rm web setup` most of it works correctly, it gets past the stage of tagging the server image `Successfully tagged asciinema/asciinema-server:latest`

But when it runs `setup` to seed the database, I get the error:

```
21:33:48.282 [error] GenServer #PID<0.224.0> terminating
** (ArgumentError) argument error
    (postgrex) lib/postgrex/utils.ex:67: anonymous fn/1 in Postgrex.Utils.parse_version/1
    (elixir) lib/enum.ex:1270: Enum."-map/2-lists^map/1-0-"/2
    (elixir) lib/enum.ex:1270: Enum."-map/2-lists^map/1-0-"/2
    (postgrex) lib/postgrex/utils.ex:67: Postgrex.Utils.parse_version/1
    (postgrex) lib/postgrex/protocol.ex:641: Postgrex.Protocol.bootstrap_send/6
    (postgrex) lib/postgrex/protocol.ex:475: Postgrex.Protocol.handshake/2
    (db_connection) lib/db_connection/connection.ex:134: DBConnection.Connection.connect/2
    (connection) lib/connection.ex:622: Connection.enter_connect/5
Last message: nil
** (Mix) The database for Asciinema.Repo couldn't be created: an exception was raised:
    ** (ArgumentError) argument error
        (postgrex) lib/postgrex/utils.ex:67: anonymous fn/1 in Postgrex.Utils.parse_version/1
        (elixir) lib/enum.ex:1270: Enum."-map/2-lists^map/1-0-"/2
        (elixir) lib/enum.ex:1270: Enum."-map/2-lists^map/1-0-"/2
        (postgrex) lib/postgrex/utils.ex:67: Postgrex.Utils.parse_version/1
        (postgrex) lib/postgrex/protocol.ex:641: Postgrex.Protocol.bootstrap_send/6
        (postgrex) lib/postgrex/protocol.ex:475: Postgrex.Protocol.handshake/2
        (db_connection) lib/db_connection/connection.ex:134: DBConnection.Connection.connect/2
        (connection) lib/connection.ex:622: Connection.enter_connect/5
```

I read that this may be due to permissions or a postgres user not existing in the database container, so I attach to it:

```
root@34512cad62ac:/# psql
psql: could not connect to server: No such file or directory
	Is the server running locally and accepting
	connections on Unix domain socket "/var/run/postgresql/.s.PGSQL.5432"?
```

Seems that somewhere along the line, postgres was not started/installed in the container. Can someone point me in the correct direction for more debugging?

Let me know if you need any more information

**Comment by sickill** [comment]
Have you checked out master branch or develop? I think I committed a fix for this recently to develop.

**Comment by W1lkins** [comment]
Since the instructions specified master specifically

```
git clone --recursive https://github.com/asciinema/asciinema-server.git
cd asciinema-server
git checkout master
```

I forked from there, I will give it a try with the develop branch and see how it goes

**Comment by konstest** [comment]
Hi, I try to update my Asciinema instance and i get this error when i run: **docker-compose run --rm web setup**:
```
root@pastebin-asciinema:/home/asciinema-server# docker-compose up -d postgres
Creating asciinema_postgres ... done
root@pastebin-asciinema:/home/asciinema-server# docker-compose run --rm web setup
Creating asciinema_redis    ... done
Starting asciinema_postgres ... done
Creating asciinema_smtp     ... done
The database for Asciinema.Repo has already been created
09:54:18.015 [error] Could not retrieve migrated versions. This error usually happens due to the following:

  * The database does not exist
  * The "schema_migrations" table, which Ecto uses for managing
    migrations, was defined by another library

To fix the first issue, run "mix ecto.create".

To address the second, you can run "mix ecto.drop" followed by
"mix ecto.create". Alternatively you may configure Ecto to use
another table for managing migrations:

    config :asciinema, Asciinema.Repo,
      migration_source: "some_other_table_for_schema_migrations"

The full error report is shown below.

** (ArgumentError) cannot load `"20111123210607"` as type :integer
    (ecto) lib/ecto/repo/queryable.ex:313: Ecto.Repo.Queryable.load!/5
    (ecto) lib/ecto/repo/queryable.ex:255: Ecto.Repo.Queryable.process/5
    (ecto) lib/ecto/repo/queryable.ex:189: anonymous fn/4 in Ecto.Repo.Queryable.postprocessor/4
    (elixir) lib/enum.ex:1270: Enum."-map/2-lists^map/1-0-"/2
    (ecto) lib/ecto/repo/queryable.ex:139: Ecto.Repo.Queryable.execute/5
    (ecto) lib/ecto/repo/queryable.ex:37: Ecto.Repo.Queryable.all/4
    (ecto) lib/ecto/migrator.ex:300: Ecto.Migrator.verbose_schema_migration/3
    (ecto) lib/ecto/migrator.ex:157: Ecto.Migrator.run/4
```
If i clean volumes/* dir it works correctly, but i need to have my old asciinema videos from old instance.

**Comment by sickill** [comment]
@W1lkins I've just updated doc, tagged current develop and merged it to master. Docker hub already built updated image. You can try this now:

```
git checkout master
git pull
docker pull asciinema/asciinema-server:latest
docker-compose run --rm phoenix setup
```

**Comment by sickill** [comment]
@konstest ok, I see you're running the code from before the database migrations have been moved from ActiveRecord to Ecto.

Let's try the following.

Create `docker-compose-2.yml` in your checkout directory with the following contents:

```yml
version: '2'

services:
  postgres:
    image: postgres
    container_name: asciinema_postgres
    restart: unless-stopped
    volumes:
      - ./volumes/postgres:/var/lib/postgresql/data

  web:
    image: asciinema/asciinema-server:final-rails-migration
    container_name: asciinema_upgrade
    restart: unless-stopped
    links:
      - postgres
    env_file: .env.production
    volumes:
      - ./uploads:/app/uploads
      - /tmp/asciinema-web:/tmp
```

You may want to adjust database volume mapping if you've changed it locally.

Then run old ActiveRecord migrations, up to the final one:

```
docker-compose -f docker-compose-2.yml run --rm web upgrade
```

Now, run all recent Ecto migrations:

```
git checkout master
git pull
docker pull asciinema/asciinema-server:latest
docker-compose run --rm phoenix upgrade
```

**Comment by W1lkins** [comment]
This resolved it, thanks! 🎉
