### ISSUE TITLE
(Postgrex.Error) ERROR 42P01 (undefined_table) relation "public.oban_jobs" does not exist

### ISSUE THREAD

**Issue by lvnilesh** [asciinema/asciinema-server#381]
I put these three files in a folder.

`.env.production` from https://github.com/asciinema/asciinema-server/blob/develop/.env.production.sample 
`docker-compose.yml` from https://github.com/asciinema/asciinema-server/blob/develop/docker-compose.yml
`docker/nginx/asciinema.conf` from https://github.com/asciinema/asciinema-server/blob/develop/docker/nginx/asciinema.conf

and started up docker-compose. 

```
docker-compose up


Starting asciinema_smtp     ... done
Starting asciinema_postgres ... done
Starting asciinema_phoenix  ... done
Starting asciinema_nginx    ... done
Attaching to asciinema_smtp, asciinema_postgres, asciinema_phoenix, asciinema_nginx
asciinema_postgres | The files belonging to this database system will be owned by user "postgres".
asciinema_postgres | This user must also own the server process.
asciinema_postgres | 
asciinema_smtp | + sed -ri '
asciinema_smtp |        s/^#?(dc_local_interfaces)=.*/\1='\''[0.0.0.0]:25 ; [::0]:25'\''/;
asciinema_smtp |        s/^#?(dc_other_hostnames)=.*/\1='\'''\''/;
asciinema_smtp |        s/^#?(dc_relay_nets)=.*/\1='\''172.20.0.3\/16'\''/;
asciinema_smtp |        s/^#?(dc_eximconfig_configtype)=.*/\1='\''internet'\''/;
asciinema_smtp | ' /etc/exim4/update-exim4.conf.conf
asciinema_smtp | + update-exim4.conf -v
asciinema_smtp | using non-split configuration scheme from /etc/exim4/exim4.conf.template
asciinema_smtp |     1 LOG: MAIN
asciinema_smtp |     1   exim 4.92 daemon started: pid=1, -q15m, listening for SMTP on port 25 (IPv6 and IPv4)
asciinema_postgres | The database cluster will be initialized with locale "en_US.utf8".
asciinema_postgres | The default database encoding has accordingly been set to "UTF8".
asciinema_postgres | The default text search configuration will be set to "english".
asciinema_postgres | 
asciinema_postgres | Data page checksums are disabled.
asciinema_postgres | 
asciinema_postgres | fixing permissions on existing directory /var/lib/postgresql/data ... ok
asciinema_postgres | creating subdirectories ... ok
asciinema_postgres | selecting default max_connections ... 100
asciinema_postgres | selecting default shared_buffers ... 128MB
asciinema_postgres | selecting dynamic shared memory implementation ... posix
asciinema_postgres | creating configuration files ... ok
asciinema_postgres | running bootstrap script ... ok
asciinema_postgres | performing post-bootstrap initialization ... sh: locale: not found
asciinema_postgres | 2021-08-21 18:37:30.895 UTC [27] WARNING:  no usable system locales were found
asciinema_postgres | ok
asciinema_postgres | syncing data to disk ... ok
asciinema_postgres | 
asciinema_postgres | Success. You can now start the database server using:
asciinema_postgres | 
asciinema_postgres |     pg_ctl -D /var/lib/postgresql/data -l logfile start
asciinema_postgres | 
asciinema_postgres | 
asciinema_postgres | WARNING: enabling "trust" authentication for local connections
asciinema_postgres | You can change this by editing pg_hba.conf or using the option -A, or
asciinema_postgres | --auth-local and --auth-host, the next time you run initdb.
asciinema_postgres | ****************************************************
asciinema_postgres | WARNING: No password has been set for the database.
asciinema_postgres |          This will allow anyone with access to the
asciinema_postgres |          Postgres port to access your database. In
asciinema_postgres |          Docker's default configuration, this is
asciinema_postgres |          effectively any other container on the same
asciinema_postgres |          system.
asciinema_postgres | 
asciinema_postgres |          Use "-e POSTGRES_PASSWORD=password" to set
asciinema_postgres |          it in "docker run".
asciinema_postgres | ****************************************************
asciinema_postgres | waiting for server to start....2021-08-21 18:37:37.737 UTC [32] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
asciinema_postgres | 2021-08-21 18:37:37.770 UTC [33] LOG:  database system was shut down at 2021-08-21 18:37:36 UTC
asciinema_postgres | 2021-08-21 18:37:37.783 UTC [32] LOG:  database system is ready to accept connections
asciinema_postgres |  done
asciinema_postgres | server started
asciinema_postgres | 
asciinema_postgres | /usr/local/bin/docker-entrypoint.sh: ignoring /docker-entrypoint-initdb.d/*
asciinema_postgres | 
asciinema_postgres | waiting for server to shut down....2021-08-21 18:37:37.833 UTC [32] LOG:  received fast shutdown request
asciinema_postgres | 2021-08-21 18:37:37.835 UTC [32] LOG:  aborting any active transactions
asciinema_postgres | 2021-08-21 18:37:37.839 UTC [32] LOG:  worker process: logical replication launcher (PID 39) exited with exit code 1
asciinema_postgres | 2021-08-21 18:37:37.839 UTC [34] LOG:  shutting down
asciinema_postgres | 2021-08-21 18:37:37.863 UTC [32] LOG:  database system is shut down
asciinema_postgres |  done
asciinema_postgres | server stopped
asciinema_postgres | 
asciinema_postgres | PostgreSQL init process complete; ready for start up.
asciinema_postgres | 
asciinema_postgres | 2021-08-21 18:37:37.946 UTC [1] LOG:  listening on IPv4 address "0.0.0.0", port 5432
asciinema_postgres | 2021-08-21 18:37:37.946 UTC [1] LOG:  listening on IPv6 address "::", port 5432
asciinema_postgres | 2021-08-21 18:37:37.951 UTC [1] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
asciinema_postgres | 2021-08-21 18:37:37.982 UTC [41] LOG:  database system was shut down at 2021-08-21 18:37:37 UTC
asciinema_postgres | 2021-08-21 18:37:37.997 UTC [1] LOG:  database system is ready to accept connections
asciinema_phoenix | 18:37:39.155 [info] Running AsciinemaWeb.Endpoint with cowboy 2.8.0 at 0.0.0.0:4000 (http)
asciinema_phoenix | 18:37:39.157 [info] Access AsciinemaWeb.Endpoint at http://localhost:3000
asciinema_postgres | 2021-08-21 18:37:40.161 UTC [48] ERROR:  relation "public.oban_jobs" does not exist at character 8
asciinema_postgres | 2021-08-21 18:37:40.161 UTC [48] STATEMENT:  UPDATE "public"."oban_jobs" AS o0 SET "state" = $1 WHERE (o0."state" IN ('scheduled','retryable')) AND (NOT (o0."queue" IS NULL)) AND (o0."scheduled_at" <= $2)
asciinema_phoenix | 18:37:40.162 [error] GenServer {Oban.Registry, {Oban, {:plugin, Oban.Plugins.Stager}}} terminating
asciinema_phoenix | ** (Postgrex.Error) ERROR 42P01 (undefined_table) relation "public.oban_jobs" does not exist
asciinema_phoenix | 
asciinema_phoenix |     query: UPDATE "public"."oban_jobs" AS o0 SET "state" = $1 WHERE (o0."state" IN ('scheduled','retryable')) AND (NOT (o0."queue" IS NULL)) AND (o0."scheduled_at" <= $2)
asciinema_phoenix |     (ecto_sql 3.4.5) lib/ecto/adapters/sql.ex:593: Ecto.Adapters.SQL.raise_sql_call_error/1
asciinema_phoenix |     (ecto_sql 3.4.5) lib/ecto/adapters/sql.ex:526: Ecto.Adapters.SQL.execute/5
asciinema_phoenix |     (oban 2.6.1) lib/oban/plugins/stager.ex:87: anonymous fn/1 in Oban.Plugins.Stager.lock_and_stage/1
asciinema_phoenix |     (ecto_sql 3.4.5) lib/ecto/adapters/sql.ex:875: anonymous fn/3 in Ecto.Adapters.SQL.checkout_or_transaction/4
asciinema_phoenix |     (db_connection 2.2.2) lib/db_connection.ex:1427: DBConnection.run_transaction/4
asciinema_phoenix |     (oban 2.6.1) lib/oban/plugins/stager.ex:70: anonymous fn/2 in Oban.Plugins.Stager.handle_info/2
asciinema_phoenix |     (telemetry 0.4.3) /opt/app/deps/telemetry/src/telemetry.erl:272: :telemetry.span/3
asciinema_phoenix |     (oban 2.6.1) lib/oban/plugins/stager.ex:69: Oban.Plugins.Stager.handle_info/2
asciinema_phoenix | Last message: :stage

^CGracefully stopping... (press Ctrl+C again to force)
ERROR: Aborting.
```

**Comment by gpr** [comment]
`docker-compose run --rm phoenix setup`
