### ISSUE TITLE
 Asciinema server can't determine pg master after swittch 

### ISSUE THREAD

**Issue by s2face** [asciinema/asciinema-server#449]
asciinema server don't switch to new pg master.
After switching maser to previous -> server continue work fine

1. setup DATABASE_URL=postgresql://user:password@host1:6432,host2:6432,host3:6432/asciinema 
2. start server
3. switch pg master
4. See error:
`** (Postgrex.Error) ERROR 25006 (read_only_sql_transaction) cannot execute UPDATE in a read-only transaction
    (ecto_sql 3.10.1) lib/ecto/adapters/sql.ex:913: Ecto.Adapters.SQL.raise_sql_call_error/1
    (ecto_sql 3.10.1) lib/ecto/adapters/sql.ex:828: Ecto.Adapters.SQL.execute/6
    (ecto 3.10.3) lib/ecto/repo/queryable.ex:229: Ecto.Repo.Queryable.execute/4
    (oban 2.15.2) lib/oban/engines/basic.ex:119: anonymous fn/4 in Oban.Engines.Basic.fetch_jobs/3
    (ecto_sql 3.10.1) lib/ecto/adapters/sql.ex:1203: anonymous fn/3 in Ecto.Adapters.SQL.checkout_or_transaction/4
    (db_connection 2.5.0) lib/db_connection.ex:1630: DBConnection.run_transaction/4
    (oban 2.15.2) lib/oban/engine.ex:219: anonymous fn/4 in Oban.Engine.fetch_jobs/3
    (oban 2.15.2) lib/oban/engine.ex:314: anonymous fn/3 in Oban.Engine.with_span/4`

**Expected behavior**
I expect that server automatically discover new pg master and switch to it

**Versions:**
 - Ubuntu 22.04

**Comment by s2face** [comment]
After switching maser to previous -> server continue work fine

**Comment by ku1ik** [comment]
The database library (Ecto) doesn't support this unfortunately and there's not much we can do here. 

If you want automatic switch then I what you can do is to setup log monitoring and force container restart when "UPDATE in a read-only transaction" message shows up.
